//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrators
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Administrators()
        {
            this.Orderinfo = new HashSet<Orderinfo>();
        }
    
        public int ManagerID { get; set; }
        public string ManagerName { get; set; }
        public string Managernumber { get; set; }
        public string Managerloginnuber { get; set; }
        public string ManagerrPwd { get; set; }
        public string ManagerEmail { get; set; }
        public string Managerphoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderinfo> Orderinfo { get; set; }
    }
}
