//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenMall.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GreenMallEntities : DbContext
    {
        public GreenMallEntities()
            : base("name=GreenMallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrators> Administrators { get; set; }
        public virtual DbSet<Billinfo> Billinfo { get; set; }
        public virtual DbSet<Goodstype> Goodstype { get; set; }
        public virtual DbSet<Orderinfo> Orderinfo { get; set; }
        public virtual DbSet<Recordsinfo> Recordsinfo { get; set; }
        public virtual DbSet<Shopinginfo> Shopinginfo { get; set; }
        public virtual DbSet<Useerinfo> Useerinfo { get; set; }
    }
}
