//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orderinfo()
        {
            this.Billinfo = new HashSet<Billinfo>();
        }
    
        public int OrderID { get; set; }
        public string GoodsName { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GoodsID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public System.DateTime Ordertime { get; set; }
        public int Oderstate { get; set; }
        public Nullable<decimal> Payable { get; set; }
        public Nullable<decimal> Hnrb { get; set; }
        public Nullable<decimal> Tobepaid { get; set; }
        public string Paymentmethod { get; set; }
        public string Notes { get; set; }
        public Nullable<int> GoodsNumber { get; set; }
    
        public virtual Administrators Administrators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billinfo> Billinfo { get; set; }
        public virtual Shopinginfo Shopinginfo { get; set; }
        public virtual Useerinfo Useerinfo { get; set; }
    }
}
