//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordsinfo
    {
        public int Merchantsid { get; set; }
        public string MerchantsName { get; set; }
        public Nullable<int> MerchantsType { get; set; }
        public string MerchantsPhon { get; set; }
        public string MerPlantingShoping { get; set; }
    }
}
