//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopinginfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shopinginfo()
        {
            this.Orderinfo = new HashSet<Orderinfo>();
        }
    
        public int GoodsID { get; set; }
        public string GoodsName { get; set; }
        public string GoodsPicLarge { get; set; }
        public string GoodsPPicSmall { get; set; }
        public string GoodsVideo { get; set; }
        public Nullable<int> TyIpeD { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Goodstype Goodstype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderinfo> Orderinfo { get; set; }
    }
}
